name: type21
description: From Type2
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  http: ^1.1.0
  get: ^4.6.6
  sleek_circular_slider: ^2.0.1
  intl: ^0.18.1
  geocoding: ^2.1.0
  google_maps_flutter: any
  google_maps_utils: ^1.5.1+0
  geolocator: any
  provider: any
  firebase_crashlytics: ^3.3.5
  form_field_validator: ^1.1.0
  fluttertoast: ^8.2.2
  firebase_analytics: ^10.4.5
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  firebase_storage: ^11.2.6
  collection: ^1.17.2
  turf: ^0.0.8
  flutter_map: ^5.0.0
  cloud_firestore: ^4.9.1
  google_fonts: ^5.1.0
  fl_chart: ^0.63.0
  firebase_database: ^10.2.5
  logger: ^2.0.2
  table_calendar: ^3.0.9
  syncfusion_flutter_charts: ^23.1.36
  simple_gesture_detector: any
  dartx: any
  flutter_calendar_carousel: ^2.4.2
  permission_handler: ^11.0.0
  location: ^5.0.3
  shared_preferences: ^2.2.1
  google_sign_in: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3

flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/weather/
    - assets/images/
    - assets/map_style.txt
    - assets/locations.json
    - assets/fonts/
  fonts:
    - family: Jasmine
      fonts:
        - asset: assets/fonts/Jasmine.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
